---
- name: Install supervisord
  apt: pkg=supervisor state=installed update_cache=true

- name: Template out supervisor configuration
  template: src={{ service_conf }} dest=/etc/supervisor/conf.d/{{ service_conf }}
  notify:
    - Restart {{ service }}

- name: Enable supervisord
  service: name=supervisor enabled=yes

- name: Start supervisord
  service: name=supervisor state=started
