---
- name: Assure existence of linkalytics directory
  file: path=/home/ansible/linkalytics/ state=directory

- name: Copy requirements
  copy: src=../../requirements.txt dest=/home/ansible/requirements.txt

- name: Copy worker
  synchronize: src=../../linkalytics/ dest=/home/ansible/linkalytics/
  notify:
    - Restart dqworker

- name: Install Enchant Dictionaries
  apt: pkg=libenchant1c2a state=installed update_cache=true

- name: Install pandas
  apt: pkg=python3-pandas state=installed update_cache=true

- name: Install scipy
  apt: pkg=python3-scipy state=installed update_cache=true

- name: Install dependencies
  pip: requirements=/home/ansible/requirements.txt executable=pip3

- name: Install English stopwords via nltk
  command: sudo python3 -m nltk.downloader -d /usr/local/share/nltk_data stopwords
