---
- name: Assure existence of linkalytics directory
  file: path=/home/ansible/linkalytics/ state=directory

- name: Copy requirements
  copy: src=../../requirements.txt dest=/home/ansible/requirements.txt

- name: Copy worker
  synchronize: src=../../linkalytics/ dest=/home/ansible/linkalytics/
  notify:
    - Restart dqworker

- name: Install dependencies
  pip: requirements=/home/ansible/requirements.txt executable=pip3

- name: Install English stopwords via nltk
  command: python3 -m nltk.downloader stopwords
